In [2]:
# Import libraries and dependencies
import pandas as pd
from pathlib import Path
import seaborn as sns
%matplotlib inline

import os
import requests
from dotenv import load_dotenv
import alpaca_trade_api as tradeapi
import seaborn as sns

%matplotlib inline

In [4]:
# Load .env environment variables
load_dotenv()

True

In [5]:
# Set Alpaca API key and secret
alpaca_api_key = os.getenv("ALPACA_API_KEY")
alpaca_secret_key = os.getenv("ALPACA_SECRET_KEY")

In [6]:
# Verify that Alpaca key and secret were correctly loaded
print(f"Alpaca Key type: {type(alpaca_api_key)}")
print(f"Alpaca Secret Key type: {type(alpaca_secret_key)}")

Alpaca Key type: <class 'str'>
Alpaca Secret Key type: <class 'str'>

In [7]:
# Create the Alpaca API object
alpaca = tradeapi.REST(
    alpaca_api_key,
    alpaca_secret_key,
    api_version="v2")

In [9]:
# Format current date as ISO format
start = pd.Timestamp("2015-12-01", tz="America/New_York").isoformat()
end = pd.Timestamp("2022-09-20", tz="America/New_York").isoformat()

In [12]:
# Set timeframe to one day ("1Day") for the Alpaca API
timeframe = "1Day"

In [13]:
# Set the tickers
tickers = ['SPGI',
'MCO',
'CPRT',
'EFX',
'FLT',
'CRL',
'OMC',
'IPG',
'RHI',
'NLSN',
'VZ',
'T',
'TMUS',
'LUMN',
'TSLA',
'GM',
'F',
'ATVI',
'EA',
'DHI',
'SWK',
'TTWO',
'NVR',
'LKQ',
'PHM',
'WHR',
'HAS',
'MHK',
'SNA',
'PG',
'NKE',
'KO',
'PEP',
'PM',
'EL',
'MDLZ',
'MO',
'CL',
'MNST',
'KMB',
'STZ',
'KHC',
'GIS',
'HSY',
'IFF',
'BF.B',
'TSN',
'VFC',
'HRL',
'MKC',
'CHD',
'K',
'CLX',
'CAG',
'SJM',
'CPB',
'TAP',
'LW',
'UAA',
'UA',
'PVH',
'DIS',
'CMCSA',
'MCD',
'SBUX',
'CHTR',
'BKNG',
'MAR',
'CMG',
'CTAS',
'HLT',
'YUM',
'LVS',
'EXPE',
'LYV',
'MGM',
'VIAC',
'FOX',
'FOXA',
'RCL',
'DPZ',
'CZR',
'DRI',
'DISH',
'ROL',
'NWSA',
'NWS',
'DISCA',
'DISCK',
'WYNN',
'NCLH',
'PENN',
'SYY',
'MCK',
'FAST',
'ABC',
'GWW',
'POOL',
'GPC',
'CAH',
'HSIC',
'AAPL',
'NVDA',
'AVGO',
'INTC',
'QCOM',
'AMD',
'TXN',
'RTX',
'BA',
'MU',
'LRCX',
'LMT',
'ADI',
'KLAC',
'NXPI',
'NOC',
'GD',
'XLNX',
'FTNT',
'TEL',
'APH',
'MCHP',
'MSI',
'ANET',
'LHX',
'HPQ',
'KEYS',
'TDG',
'GLW',
'ZBRA',
'TER',
'SWKS',
'FTV',
'GRMN',
'STX',
'ENPH',
'MPWR',
'TRMB',
'HPE',
'TDY',
'WDC',
'NTAP',
'QRVO',
'TXT',
'FFIV',
'HWM',
'IPGP',
'HII',
'XOM',
'CVX',
'COP',
'EOG',
'PXD',
'MPC',
'PSX',
'VLO',
'DVN',
'OXY',
'HES',
'FANG',
'CTRA',
'MRO',
'APA',
'BRK.B',
'JPM',
'V',
'BAC',
'MA',
'WFC',
'MS',
'SCHW',
'BLK',
'AMT',
'GS',
'AXP',
'PLD',
'C',
'CCI',
'PNC',
'USB',
'MMC',
'CB',
'CME',
'EQIX',
'ICE',
'PSA',
'AON',
'COF',
'PGR',
'MET',
'SPG',
'DLR',
'BK',
'AIG',
'TROW',
'SBAC',
'PRU',
'O',
'SIVB',
'AFL',
'TRV',
'WELL',
'CBRE',
'AVB',
'FRC',
'DFS',
'AJG',
'ARE',
'STT',
'AMP',
'EQR',
'ALL',
'NDAQ',
'WY',
'FITB',
'EXR',
'WLTW',
'MAA',
'SYF',
'DRE',
'NTRS',
'URI',
'HIG',
'ESS',
'RF',
'RJF',
'VTR',
'CFG',
'MTB',
'PEAK',
'BRO',
'PFG',
'SBNY',
'UDR',
'CINF',
'BXP',
'BEN',
'KIM',
'IRM',
'MKTX',
'L',
'WRB',
'CBOE',
'REG',
'LNC',
'HST',
'CMA',
'IVZ',
'RE',
'FRT',
'ZION',
'GL',
'AIZ',
'VNO',
'PBCT',
'UNH',
'ANTM',
'HCA',
'CI',
'HUM',
'IQV',
'CNC',
'LH',
'DGX',
'DVA',
'UHS',
'JNJ',
'PFE',
'LLY',
'TMO',
'ABT',
'ABBV',
'DHR',
'MRK',
'MDT',
'BMY',
'ISRG',
'AMGN',
'ZTS',
'SYK',
'MRNA',
'GILD',
'EW',
'BDX',
'REGN',
'BSX',
'ILMN',
'VRTX',
'IDXX',
'ALGN',
'DXCM',
'A',
'BAX',
'MTD',
'RMD',
'BIIB',
'WST',
'ZBH',
'STE',
'PKI',
'WAT',
'BIO',
'CTLT',
'COO',
'TECH',
'HOLX',
'VTRS',
'ABMD',
'INCY',
'TFX',
'XRAY',
'OGN',
'WM',
'SLB',
'RSG',
'KMI',
'WMB',
'OKE',
'BKR',
'HAL',
'J',
'PWR',
'FCX',
'NEM',
'NUE',
'VMC',
'MLM',
'LIN',
'SHW',
'ECL',
'APD',
'DOW',
'DD',
'PPG',
'ADM',
'CTVA',
'LYB',
'BLL',
'ALB',
'CE',
'AMCR',
'IP',
'AVY',
'EMN',
'MOS',
'CF',
'FMC',
'PKG',
'WRK',
'SEE',
'HON',
'AMAT',
'CAT',
'DE',
'GE',
'MMM',
'ITW',
'ETN',
'JCI',
'EMR',
'TT',
'CARR',
'APTV',
'PH',
'ROK',
'OTIS',
'AME',
'CMI',
'PCAR',
'DOV',
'IR',
'GNRC',
'XYL',
'IEX',
'WAB',
'MAS',
'SEDG',
'FBHS',
'AOS',
'PNR',
'ALLE',
'BWA',
'NWL',
'AMZN',
'HD',
'WMT',
'COST',
'LOW',
'CVS',
'TGT',
'TJX',
'DG',
'ORLY',
'WBA',
'AZO',
'EBAY',
'ROST',
'KR',
'DLTR',
'TSCO',
'ETSY',
'BBY',
'ULTA',
'KMX',
'BBWI',
'AAP',
'TPR',
'RL',
'GPS',
'MSFT',
'GOOG',
'GOOGL',
'FB',
'ACN',
'CSCO',
'NFLX',
'CRM',
'ORCL',
'PYPL',
'INTU',
'NOW',
'IBM',
'ADP',
'FISV',
'FIS',
'ADSK',
'SNPS',
'INFO',
'CDNS',
'ROP',
'MSCI',
'PAYX',
'CTSH',
'GPN',
'MTCH',
'EPAM',
'VRSK',
'ANSS',
'TWTR',
'VRSN',
'CDW',
'CERN',
'IT',
'PAYC',
'TYL',
'BR',
'AKAM',
'FDS',
'CDAY',
'NLOK',
'PTC',
'JKHY',
'LDOS',
'CTXS',
'JNPR',
'DXC',
'UPS',
'UNP',
'CSX',
'FDX',
'ODFL',
'LUV',
'DAL',
'EXPD',
'JBHT',
'UAL',
'CHRW',
'AAL',
'ALK',
'NEE',
'DUK',
'SO',
'D',
'EXC',
'AEP',
'SRE',
'XEL',
'PEG',
'AWK',
'ES',
'WEC',
'ED',
'EIX',
'DTE',
'AEE',
'PPL',
'FE',
'ETR',
'CMS',
'CNP',
'AES',
'EVRG',
'LNT',
'ATO',
'NI',
'NRG',
'PNW']

In [17]:
# Get current closing prices for SP500 tickers
portfolio_alpacas = alpaca.get_bars(
    tickers,
    timeframe,
    start = start,
    end = end
).df

# Display sample data
portfolio_alpacas

sleep 3 seconds and retrying https://data.alpaca.markets/v2/stocks/bars 3 more time(s)...
sleep 3 seconds and retrying https://data.alpaca.markets/v2/stocks/bars 3 more time(s)...

,open,high,low,close,volume,trade_count,vwap,symbol
timestamp,,,,,,,,
2015-12-01 05:00:00+00:00,41.47,43.300,41.300,43.26,8912859,50657,42.668365,AAL
2015-12-02 05:00:00+00:00,44.00,44.530,43.530,43.82,8010351,52209,44.032147,AAL
2015-12-03 05:00:00+00:00,43.65,44.600,42.920,43.27,7234737,47951,43.556866,AAL
2015-12-04 05:00:00+00:00,43.82,44.990,43.820,44.97,9460935,60427,44.749545,AAL
2015-12-07 05:00:00+00:00,45.35,46.490,45.220,45.78,8911719,54034,45.783429,AAL
...,...,...,...,...,...,...,...,...
2022-09-14 04:00:00+00:00,161.18,161.705,159.285,160.23,1770644,30461,160.458537,ZTS
2022-09-15 04:00:00+00:00,160.47,161.690,158.710,159.18,1627294,24566,159.626275,ZTS
2022-09-16 04:00:00+00:00,158.77,158.960,155.310,157.30,2681215,32593,157.198345,ZTS
2022-09-19 04:00:00+00:00,155.99,157.280,154.960,157.19,1608251,25807,156.345943,ZTS
2022-09-20 04:00:00+00:00,155.44,155.990,151.750,152.94,1980460,26354,153.242194,ZTS

In [18]:
#Convert data pull to CSV
portfolio_alpacas.to_csv('sp500_alpacas_2015_to_2022.csv')

In [19]:
# Set the file paths to the CSVs using the Path class from the pathlib library
sp500_csv_path = Path("../Resources/sp500_alpacas_2015_to_2022.csv")

In [22]:
# Read the data, set the `Month` as the index
sp500_df = pd.read_csv(sp500_csv_path, index_col="timestamp", infer_datetime_format=True, parse_dates=True)
sp500_df

,open,high,low,close,volume,trade_count,vwap,symbol
timestamp,,,,,,,,
2015-12-01 05:00:00+00:00,41.47,43.300,41.300,43.26,8912859,50657,42.668365,AAL
2015-12-02 05:00:00+00:00,44.00,44.530,43.530,43.82,8010351,52209,44.032147,AAL
2015-12-03 05:00:00+00:00,43.65,44.600,42.920,43.27,7234737,47951,43.556866,AAL
2015-12-04 05:00:00+00:00,43.82,44.990,43.820,44.97,9460935,60427,44.749545,AAL
2015-12-07 05:00:00+00:00,45.35,46.490,45.220,45.78,8911719,54034,45.783429,AAL
...,...,...,...,...,...,...,...,...
2022-09-14 04:00:00+00:00,161.18,161.705,159.285,160.23,1770644,30461,160.458537,ZTS
2022-09-15 04:00:00+00:00,160.47,161.690,158.710,159.18,1627294,24566,159.626275,ZTS
2022-09-16 04:00:00+00:00,158.77,158.960,155.310,157.30,2681215,32593,157.198345,ZTS
2022-09-19 04:00:00+00:00,155.99,157.280,154.960,157.19,1608251,25807,156.345943,ZTS
2022-09-20 04:00:00+00:00,155.44,155.990,151.750,152.94,1980460,26354,153.242194,ZTS